package dev.codedefense.cli;
import static org.junit.jupiter.api.Assertions.*;
import dev.codedefense.analysis.ProjectAnalyzer; import dev.codedefense.application.CodeDefenseConfig; import dev.codedefense.application.CodeDefenseRuntime; import dev.codedefense.application.DefaultProjectDefenseRunner; import dev.codedefense.domain.*; import dev.codedefense.interview.*; import dev.codedefense.scanner.*; import dev.codedefense.terminal.ProjectAnalysisRenderer;
import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.util.*; import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.io.TempDir; import picocli.CommandLine;
class StartCommandInterviewTest {
 @TempDir Path root;
 @Test void acceptedAnalysisRunsInterviewExactlyOnce() throws Exception {AtomicInteger calls=new AtomicInteger();CommandLine cli=cli(a->{calls.incrementAndGet();return null;});assertEquals(0,cli.execute("--yes",root.toString()));assertEquals(1,calls.get());}
 @Test void cancellationMapsToExit130WithoutStackTrace() throws Exception {ByteArrayOutputStream err=new ByteArrayOutputStream();CommandLine cli=cli(a->{throw new InterviewCancelledException("Session cancelled. No report was generated.");});cli.setErr(new PrintWriter(err,true,StandardCharsets.UTF_8));assertEquals(130,cli.execute("--yes",root.toString()));assertTrue(err.toString(StandardCharsets.UTF_8).contains("No report was generated"));assertFalse(err.toString(StandardCharsets.UTF_8).contains("\tat "));}
 @Test void dryRunAndDeclineNeverRunInterview() throws Exception {AtomicInteger calls=new AtomicInteger();CommandLine dry=cli(a->{calls.incrementAndGet();return null;});assertEquals(0,dry.execute("--dry-run",root.toString()));CommandLine decline=cli(a->{calls.incrementAndGet();return null;},false);assertEquals(0,decline.execute(root.toString()));assertEquals(0,calls.get());}
 private CommandLine cli(InterviewRunner runner)throws Exception{return cli(runner,true);} private CommandLine cli(InterviewRunner runner,boolean confirm)throws Exception{Path file=root.resolve("App.java");Files.writeString(file,"class App {}");long size=Files.size(file);ProjectScanner scanner=(p,policy)->new ScanSummary(root,1,0,List.of(new SourceFile(Path.of("App.java"),size)));ProjectAnalyzer analyzer=s->analysis();var workflow=new DefaultProjectDefenseRunner(scanner,new ProjectSnapshotBuilder(CodeDefenseConfig.defaults()),p->confirm,new ProjectAnalysisRenderer(),ignored->new CodeDefenseRuntime(analyzer,runner,(snapshot,analysis,session)->{throw new AssertionError("No report is expected without a report test");}));CommandLine cli=new CommandLine(new StartCommand(workflow));cli.setOut(new PrintWriter(new ByteArrayOutputStream(),true,StandardCharsets.UTF_8));return cli;}
 private static ProjectAnalysis analysis(){List<TechnicalQuestion> q=new ArrayList<>();for(int n=1;n<=3;n++)q.add(new TechnicalQuestion("q"+n,"Question prompt "+n,"Goal",List.of("one","two"),List.of(new CodeEvidence("App.java",1,1,"reason"))));return new ProjectAnalysis("demo","Java CLI","A sufficiently useful project summary.",List.of("first flow","second flow"),List.of(new ProjectComponent("App","class","Runs the application",List.of("App.java"))),List.of("startup","errors"),q);}
}
